---
- hosts: 'kubernetes'
  gather_facts: True
  become: True
  tasks:
    - name: Build K8 Cluster
      block:

        - name: Touch lock file
          when: inventory_hostname == groups[cp_group][0]
          file:
            path: "{{ lock_file }}"
            state: touch
          delegate_to: localhost

        # Create installation progress file
        - name: Touch installation status file
          when: inventory_hostname == groups[cp_group][0]
          copy:
            content: ""
            dest: "{{ status_file }}"
          delegate_to: localhost

        - name: Install All PreReqs on all hosts
          include_role: 
            name: k8_mgmt

        - name: Setup profiles on control plane nodes
          when: inventory_hostname in groups[cp_group]
          import_role: 
            name: k8_mgmt
            tasks_from: controlplane_profile_config

        - name: Initialize Kubernetes on first control plane node
          when: inventory_hostname == groups[cp_group][0]
          import_role: 
            name: k8_mgmt
            tasks_from: init_controlplane

        - name: Install helm on first control plane node
          when: inventory_hostname == groups[cp_group][0]
          include_role: 
            name: helm_install

        - name: Install helm on first control plane node
          when: inventory_hostname == groups[cp_group][0]
          include_role: 
            name: helm_install
            tasks_from: helm_install_calico

        #ansible logging feature?????
        - name: Update status of first control plane node
          when: inventory_hostname == groups[cp_group][0] and (cni_up['resources'] | length > 0)
          lineinfile:
            path: "{{ status_file }}"
            line: "cni_up"
          delegate_to: localhost

        - name: Join other control plane nodes to cluster
          when: inventory_hostname in groups[cp_group] and inventory_hostname != groups[cp_group][0]
          include_role:
            name: k8_mgmt
            tasks_from: join_cluster.yml

        - name: All worker nodes waiting for control plane nodes to complete setup
          when: inventory_hostname in groups[wk_group]
          wait_for:
            path: "{{ lock_file }}"
            state: absent
            timeout: 600
          delegate_to: localhost
        
        - name: kubeadm token create join-command
          when: inventory_hostname in groups[wk_group]
          command: kubeadm token create --print-join-command
          changed_when: False
          register: join_command
          delegate_to: "{{ groups[cp_group][0] }}"

        - name: Join other control plane nodes to cluster
          when: inventory_hostname in groups[wk_group]
          include_role:
            name: k8_mgmt
            tasks_from: join_cluster.yml
          vars:
            join_cluster_code: "{{ join_command['stdout'] }}"

      tags: create_cluster
